version: "3.8"

services:
  db:
    image: postgres:12.6-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  cache:
    image: redis:6.2-alpine
    restart: always
    environment:
      - REDIS_PASSWORD=redispassword
    command: redis-server --save 20 1 --loglevel warning --requirepass redispassword
    ports:
      - 6379:6379
    volumes:
      - cache:/data

volumes:
  postgres_data:
    driver: local
  cache:
    driver: local
