import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import trpc from '@/lib/hooks/trpc';
import { GetServerSideProps } from 'next';

export const getServerSideProps: GetServerSideProps = async () => ({
  redirect: {
    destination: '/boards',
  },
  props: {},
});

export default function Home() {
  const query = trpc.hello.useQuery({ text: 'World!' });
  if (!query.data) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Create Next App!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className="text-white bg-red-200">something</p>
      <main className={styles.main}>
        <h1>{query.data.greeting}</h1>
      </main>
    </>
  );
}
