name: CI

on:
  push:
    branches: ["dev", main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["dev"]

jobs:
  ESLint:
    name: ESLint check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install deps
        run: npm install
        working-directory: data-dashboard

      - name: Run ESLint
        run: npm run lint
        working-directory: data-dashboard
  DB-Deploy:
    name: Create preview database
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_DB_USERNAME }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_DB_PASSWORD }}
      POSTGRES_HOST: ${{ vars.POSTGRES_DB_HOST }}
      POSTGRES_PORT: 5432
      DATABASE_NAME: pr${{ github.event.number }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PostgreSQL client
      run: sudo apt-get install -y postgresql-client

    - name: Create new database
      run: |
        psql postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:5432/ -c "CREATE DATABASE $DATABASE_NAME"
