name: Create preview DB
on:
  pull_request:
    branches: ["dev"]
    types: [opened, reopened]
jobs:
  DB-Deploy:
    name: Create preview database
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_DB_USERNAME }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_DB_PASSWORD }}
      POSTGRES_HOST: ${{ vars.POSTGRES_DB_HOST }}
      POSTGRES_PORT: 5432
      DATABASE_NAME: pr${{ github.event.number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Create new database
        run: |
          psql postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST/postgres?sslmode=require -c "CREATE DATABASE $DATABASE_NAME"
